
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: "Martina Dal Bello"
subtitle: "Postdoctoral Researcher at MIT"
url: "https://martinadalbello.com" # the base hostname & protocol for your site
address: "NE46-610, 400 Technology Square, 02139 Cambridge MA, USA"
email: "dalbello@mit.edu"
twitter: "martinadalbello"
google_scholar: "mQU_Tg8AAAAJ"
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
# Google maps link from "share -> embed". Force dimensions 555px x 300 px
google_maps: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2947.995914317711!2d-71.09403304850724!3d42.36392634274712!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e370ac2269542d%3A0x4fafcb5028f3a887!2s400+Technology+Square%2C+Cambridge%2C+MA+02139!5e0!3m2!1sen!2sus!4v1551570025106" width="350" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>'
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
highlighter: rouge

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Pages
collections:
  pages:
    output: true
  research:
    output: true
    permalink: /research/:name


defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: research_page

# Scholar for Bibliography
scholar:
  style: _data/bibliography/ieee_only_author.csl  # Extract only author's name using IEEE format
  locale: en

  # sort_by: none
  order: descending
  sort_by: month
  group_by: type, year
  group_order: ascending, descending
  # type_names: { inproceedings: 'Conference Proceedings' }
  type_order: [article, thesis]
  # order: ascending
  bibliography_list_tag: ul
  bibliography_item_tag: li
  bibliography_group_tag: h2, h3

  source: _data/bibliography
  bibliography: bibliography.bib
  bibliography_template: bibliography_entry
  parse_names: true
  replace_strings: true
  join_strings:    true
  query: "@*"

